default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: 5
  username: <%= ENV['RAILS_DATABASE_USER'] %>
  password: <%= ENV['RAILS_DATABASE_PASSWORD'] %>
  socket: /tmp/mysql.sock

production:
  <<: *default
  database: escapism_production
  username: <%= ENV['RAILS_DATABASE_USER'] %>
  password: <%= ENV['RAILS_DATABASE_PASSWORD'] %>
